"""Figures, LaTeX tables and in-text number macros generated from results."""
from __future__ import annotations

import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from . import figstyle as fs
from .data import ANNUAL_YEARS, RISE_ANNUAL_YEARS, RISE_YEARS
from .figstyle import C_POL as C1, C_SHR as C2, C_CO2 as C3, C_GREY as CG, C_AMBER


def _save(fig, out):
    """600-dpi RGB PNG at the text width (see figstyle)."""
    fs.save(fig, out)


def tex_escape(s: str) -> str:
    """Escape a label for LaTeX and typeset parameters, ranges and symbols as math."""
    s = str(s).replace("&", r"\&").replace("%", r"\%").replace("_", r"\_")
    s = s.replace("CO2", r"CO$_2$").replace("Szmidt-Kacprzyk", "Szmidt--Kacprzyk")
    s = s.replace("min-max", "min--max").replace("pi-sensitive", r"$\pi$-sensitive")
    s = re.sub(r"(\d{4})-(\d{4})", r"\1--\2", s)                      # year ranges
    sym = {"kappa": r"\kappa", "lambda": r"\lambda", "eps": r"\varepsilon", "theta": r"\theta",
           "p1": "p_1", "q": "q", "v": "v", "m": "m"}
    s = re.sub(r"\b(kappa|lambda|eps|theta|p1|q|v|m)=([0-9.]+)",
               lambda g: "$" + sym[g.group(1)] + "=" + g.group(2) + "$", s)
    return s


# Display labels of the sensitivity specifications, shared by Table 6 and Figure 8
ROBUST_LABEL = {
    "Temporal: uniform": "Temporal weights: uniform",
    "Temporal: linear recency": "Temporal weights: linear recency",
    "Temporal: exponential recency (0.8)": "Temporal weights: exponential recency (0.8)",
    "Staleness decay lambda=0.10": r"Staleness decay, $\lambda=0.10$",
    "Staleness decay lambda=0.25": r"Staleness decay, $\lambda=0.25$",
    "Staleness decay lambda=0.50": r"Staleness decay, $\lambda=0.50$",
    "Per-period min-max normalisation": "Per-period min--max normalisation",
    f"Pooled min-max normalisation {ANNUAL_YEARS[0]}-{ANNUAL_YEARS[-1]}": f"Pooled min--max normalisation, {ANNUAL_YEARS[0]}--{ANNUAL_YEARS[-1]}",
    "Membership floor eps=0.001": r"Membership floor, $\varepsilon=0.001$",
    "Membership floor eps=0.05": r"Membership floor, $\varepsilon=0.05$",
    "Hesitancy kappa=0 (crisp geometric)": r"Hesitancy scale, $\kappa=0$ (crisp geometric)",
    "Hesitancy kappa=0.10": r"Hesitancy scale, $\kappa=0.10$",
    "Hesitancy kappa=0.50": r"Hesitancy scale, $\kappa=0.50$",
    "Criterion weights equal": "Equal criterion weights",
    f"Policy observed annually {RISE_ANNUAL_YEARS[0]}-{RISE_ANNUAL_YEARS[-1]} (Data360 series)": f"Policy observed annually, {RISE_ANNUAL_YEARS[0]}--{RISE_ANNUAL_YEARS[-1]} (Data360)",
    "CO2 per capita log-transformed": r"CO$_2$ per capita, log-transformed",
}


def robust_label(spec: str) -> str:
    """Display label of a sensitivity specification (LaTeX), including the
    data-definition runs whose subset size m is computed at run time."""
    if spec in ROBUST_LABEL:
        return ROBUST_LABEL[spec]
    g = re.fullmatch(r"Alternative share RE/\(RE\+fossil\), IMF dashboard \(m=(\d+)\)", spec)
    if g:
        return rf"Renewable share RE/(RE+fossil), IMF data ($m={g.group(1)}$)"
    g = re.fullmatch(r"Non-hydro renewable share \(m=(\d+)\)", spec)
    if g:
        return rf"Non-hydro renewable share ($m={g.group(1)}$)"
    if spec == "CO2 goalposts [0, 25] t":
        return r"CO$_2$ goalposts $[0,25]$ t per capita"
    g = re.fullmatch(r"Policy = RISE 2016 database, p1=1 \(m=(\d+)\)", spec)
    if g:
        return rf"Policy from the RISE 2016 database, $p_1=1$ ($m={g.group(1)}$)"
    return tex_escape(spec)


def f3(x):
    """Three decimals; a leading minus sign is typeset as a proper minus."""
    if pd.isna(x):
        return "--"
    s = f"{x:.3f}"
    return r"$-$" + s[1:] if s.startswith("-") else s


def write_table(path: Path, header: list[str], rows: list[list[str]], colspec: str):
    lines = [r"\begin{tabular}{" + colspec + "}", r"\toprule",
             " & ".join(header) + r" \\", r"\midrule"]
    for r in rows:
        if r == "MIDRULE":
            lines.append(r"\midrule")
        else:
            lines.append(" & ".join(r) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


class Macros:
    def __init__(self):
        self.items = {}

    def add(self, name, value, fmt="{:.3f}"):
        assert name.isalpha(), name
        v = fmt.format(value) if not isinstance(value, str) else value
        if v.startswith("-") and v[1:2].isdigit():      # proper minus in text and math mode
            v = r"\ensuremath{-}" + v[1:]
        self.items[name] = v

    def write(self, path: Path):
        lines = ["% Auto-generated by run_all.py -- do not edit by hand"]
        for k, v in self.items.items():
            lines.append(rf"\newcommand{{\{k}}}{{{v}}}")
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
def fig_temporal_weights(wt: pd.DataFrame, out: Path):
    fig, axes = fs.figure(2.35, ncols=2, gridspec_kw={"width_ratios": [1, 1.6]})
    p = wt[wt.criterion.str.startswith("Policy")]
    axes[0].plot(p.year, p.weight, "o-", color=C1, label="Policy (RISE)")
    axes[0].axhline(1 / len(p), ls="--", color=CG, lw=0.8, label=rf"Uniform, $1/{len(p)}$")
    axes[0].set_title(r"(a) Policy criterion, $T_1$ (RISE reference years)")
    axes[0].set_xticks(p.year); axes[0].set_xlabel("Year"); axes[0].set_ylabel(r"Temporal weight $w^{(j)}_t$")
    axes[0].legend(loc="upper right")
    for name, col, mk, lab in [("Renewable", C2, "o", "Renewable share"), ("CO2", C3, "s", r"CO$_2$ per capita")]:
        q = wt[wt.criterion.str.contains(name)]
        axes[1].plot(q.year, q.weight, marker=mk, color=col, label=lab)
    axes[1].axhline(1 / len(ANNUAL_YEARS), ls="--", color=CG, lw=0.8, label=rf"Uniform, $1/{len(ANNUAL_YEARS)}$")
    axes[1].set_title(r"(b) Annual criteria, $T_2=T_3$")
    axes[1].set_xticks(ANNUAL_YEARS); axes[1].set_xlabel("Year"); axes[1].set_ylabel(r"Temporal weight $w^{(j)}_t$")
    axes[1].legend(loc="lower left")
    _save(fig, out)


def fig_top20(primary: pd.DataFrame, smaa: pd.DataFrame, out: Path):
    top = primary.head(20).iloc[::-1]
    acc = smaa.set_index("ISO3").loc[top.ISO3, "top10_acceptability"].to_numpy()
    fig, axes = fs.figure(3.9, ncols=2, sharey=True, gridspec_kw={"width_ratios": [1.3, 1]})
    y = np.arange(len(top))
    axes[0].barh(y, top.Score, color=C1, height=0.7)
    axes[0].set_yticks(y); axes[0].set_yticklabels([f"{r}. {c}" for r, c in zip(top.Rank, top.Country)])
    axes[0].set_xlabel(r"Final score $S(\gamma)=\mu-\nu$"); axes[0].axvline(0, color="k", lw=0.5)
    axes[0].set_title("(a) Final score of the top 20 countries")
    axes[1].barh(y, acc, color=C2, height=0.7)
    axes[1].set_xlim(0, 1); axes[1].set_xlabel(r"Share of weight draws with rank $r\leq 10$")
    axes[1].set_title("(b) SMAA-2 top-10 acceptability")
    _save(fig, out)


def fig_perturbation(pr: pd.DataFrame, out: Path):
    fig, axes = fs.figure(2.45, ncols=2)
    for name, col, mk in [("policy", C1, "o"), ("share", C2, "s"), ("co2", C3, "^")]:
        axes[0].plot(pr.delta, pr[f"max_dw_{name}"], marker=mk, color=col,
                     label={"policy": "Policy (RISE)", "share": "Renewable share", "co2": r"CO$_2$ per capita"}[name])
    axes[0].set_xlabel(r"Perturbation size $\delta$")
    axes[0].set_ylabel(r"Max. $\Vert w^{(j)}-\tilde{w}^{(j)}\Vert_1$")
    axes[0].set_title("(a) Change of the temporal weights"); axes[0].legend(loc="upper left")
    axes[1].plot(pr.delta, pr.mean_tau, "o-", color=C1, label=r"Mean Kendall’s $\tau$")
    axes[1].plot(pr.delta, pr.min_tau, "v--", color=C1, alpha=0.6, label=r"Min. Kendall’s $\tau$")
    axes[1].set_ylabel(r"Kendall’s $\tau$")
    ax2 = axes[1].twinx(); ax2.plot(pr.delta, pr.mean_top10, "s-", color=C3, label="Top-10 overlap (%)")
    ax2.set_ylim(80, 101); ax2.spines["right"].set_visible(True); ax2.set_ylabel("Top-10 overlap (%)")
    axes[1].set_xlabel(r"Perturbation size $\delta$"); axes[1].set_title("(b) Stability of the ranking")
    h1, l1 = axes[1].get_legend_handles_labels(); h2, l2 = ax2.get_legend_handles_labels()
    axes[1].legend(h1 + h2, l1 + l2, loc="lower left")
    _save(fig, out)


def fig_simulation(sim: pd.DataFrame, out: Path):
    lab = {"proposed": r"Proposed (criterion-specific $T_j$)", "interpolate": "Linear interpolation",
           "align": "Common-period alignment", "omit": "Omit sparse criteria",
           "proposed_uniform": "Proposed, uniform temporal weights"}
    col = {"proposed": C1, "proposed_uniform": C_AMBER, "interpolate": C2, "align": "#C0503F", "omit": "#7B61A8"}
    fig, axes = fs.figure(2.95, ncols=2, sharey=True)
    for k, (ax, sg) in enumerate(zip(axes, sorted(sim.sigma.unique()))):
        g = sim[sim.sigma == sg].groupby(["p_sparse", "method"]).tau.mean().unstack()
        for mth, st in [("proposed", "o-"), ("proposed_uniform", "o:"), ("interpolate", "s--"),
                        ("align", "^-."), ("omit", "x-")]:
            ax.plot(g.index, g[mth], st, color=col[mth], label=lab[mth])
        ax.set_xticks(g.index); ax.set_xlabel(r"Observations of each sparse criterion, $p_s$")
        ax.set_title(rf"({'ab'[k]}) Noise level $\sigma={sg}$")
    axes[0].set_ylabel(r"Kendall’s $\tau$ with the true ranking")
    h, l = axes[0].get_legend_handles_labels()
    fig.legend(h, l, loc="outside lower center", ncol=3)      # below the panels, clear of the curves
    _save(fig, out)
