"""World map, policy matrix and policy-profile table (600-dpi PNG and LaTeX).

Reads outputs/tables/full_ranking.csv (written by run_all.py) and the Natural Earth
1:110m country boundaries in data/external (public domain) and writes
  outputs/figures/fig_world_map.png       final score by country (Figure 6)
  outputs/figures/fig_policy_matrix.png   RISE (last reference year) vs renewable share (last year) (Figure 13)
  outputs/tex/tab_policy_groups.tex       policy-profile table (Table 17)
  outputs/tables/policy_groups.csv        the same table as CSV
Run from the bundle root after run_all.py:  python scripts/make_policy_and_map.py
"""
import os


def save_png(fig, name):
    fs.save(fig, os.path.join(FIG, name))


def num(x, d):
    """Format a number for LaTeX with a proper minus sign."""
    s = f"{x:.{d}f}"
    return s.replace("-", "$-$")
import sys
import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))
from difss import figstyle as fs                                    # noqa: E402
from difss.data import ANNUAL_YEARS, RISE_YEARS                    # noqa: E402
RY, AY = RISE_YEARS[-1], ANNUAL_YEARS[-1]
import matplotlib.pyplot as plt                                    # noqa: E402
from matplotlib.colors import Normalize                            # noqa: E402
from matplotlib.patches import Rectangle                           # noqa: E402

DATA = os.path.join(ROOT, "outputs", "tables")
EXT = os.path.join(ROOT, "data", "external")
FIG = os.path.join(ROOT, "outputs", "figures")
TAB = os.path.join(ROOT, "outputs", "tex")
CMAP = plt.get_cmap("viridis")

df = pd.read_csv(os.path.join(DATA, "full_ranking.csv"))
norm = Normalize(vmin=df.Score.min(), vmax=df.Score.max())

# ---------------------------------------------------------------- policy groups
BANDS = ["Weak, $[0,34)$", "Intermediate, $[34,67)$", "Strong, $[67,100]$"]
df["band"] = pd.cut(df.RISE_last, [0, 34, 67, 100.01], right=False, labels=BANDS)
df["re_hi"] = df.REshare_last >= 50

rows = []
for band in reversed(BANDS):
    for hi in (True, False):
        s = df[(df.band == band) & (df.re_hi == hi)].sort_values("Rank")
        if s.empty:
            continue
        ex = ", ".join(f"{c} ({r})" for c, r in zip(s.Country.head(3), s.Rank.head(3)))
        rows.append(dict(band=band, re=r"$\geq$50" if hi else r"$<$50", n=len(s),
                         rise=s.RISE_last.mean(), share=s.REshare_last.mean(),
                         co2=s.CO2pc_last.mean(), score=s.Score.mean(),
                         med=s.Rank.median(), top20=int((s.Rank <= 20).sum()), ex=ex))
g = pd.DataFrame(rows)
with open(os.path.join(TAB, "tab_policy_groups.tex"), "w", encoding="utf-8") as f:
    f.write("% Auto-generated by scripts/make_policy_and_map.py\n")
    f.write("\\begin{tabular}{@{}llrrrrrrr>{\\raggedright\\arraybackslash}p{3.3cm}@{}}\n\\toprule\n")
    two = lambda a, b: "\\begin{tabular}[b]{@{}c@{}}" + a + "\\\\" + b + "\\end{tabular}"
    f.write(f"RISE {RY} band & " + two("RE share", "(\\%)") + " & $n$ & RISE & RE\\% & \\COtwo{} (t) & "
            "$S(\\gamma)$ & " + two("Median", "rank") + " & Top 20 & Highest-ranked countries (rank) \\\\\n\\midrule\n")
    prev = None
    for r in g.itertuples():
        lab = r.band if r.band != prev else ""
        if prev is not None and r.band != prev:
            f.write("\\addlinespace\n")
        prev = r.band
        f.write(f"{lab} & {r.re} & {r.n} & {r.rise:.1f} & {r.share:.1f} & {r.co2:.2f} & "
                f"{num(r.score, 3)} & {r.med:.0f} & {r.top20} & {r.ex} \\\\\n")
    f.write("\\midrule\n")
    f.write(f"All countries & & {len(df)} & {df.RISE_last.mean():.1f} & {df.REshare_last.mean():.1f} & "
            f"{df.CO2pc_last.mean():.2f} & {num(df.Score.mean(), 3)} & {df.Rank.median():.0f} & 20 & \\\\\n")
    f.write("\\bottomrule\n\\end{tabular}\n")
g.to_csv(os.path.join(DATA, "policy_groups.csv"), index=False)

# number macros for the policy paragraph of Section 9.2 (typeset from this file)
def _mac(name, v):
    v = str(v)
    if v.startswith("-"):                                      # proper minus for negative numbers
        v = "\\ensuremath{-}" + v[1:]
    return "\\newcommand{\\" + name + "}{" + v + "}"
tags = {(BANDS[2], True): "SH", (BANDS[2], False): "SL", (BANDS[1], True): "IH", (BANDS[1], False): "IL",
        (BANDS[0], True): "WH", (BANDS[0], False): "WL"}
lines = ["% Auto-generated by scripts/make_policy_and_map.py -- do not edit by hand"]
for r in g.itertuples():
    t = tags[(r.band, r.re == r"$\geq$50")]
    lines += [_mac(f"Pg{t}Share", f"{r.share:.1f}"), _mac(f"Pg{t}N", r.n), _mac(f"Pg{t}Score", f"{r.score:.3f}"), _mac(f"Pg{t}Med", f"{r.med:.0f}"),
              _mac(f"Pg{t}Top", r.top20), _mac(f"Pg{t}Co", f"{r.co2:.2f}"), _mac(f"Pg{t}Ex", r.ex)]
with open(os.path.join(TAB, "numbers_policy.tex"), "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

# ---------------------------------------------------------------- policy matrix
fig, ax = fs.figure(4.1)
shade = {0: "#fdecea", 34: "#fff6e0", 67: "#e8f5ec"}
for x0, x1 in [(0, 34), (34, 67), (67, 100)]:
    ax.add_patch(Rectangle((x0, 0), x1 - x0, 102, color=shade[x0], zorder=0, lw=0))
ax.axhline(50, color="0.45", lw=0.8, ls="--", zorder=1)
for x in (34, 67):
    ax.axvline(x, color="0.45", lw=0.8, ls=":", zorder=1)
size = 12 + 9 * np.sqrt(df.CO2pc_last)
sc = ax.scatter(df.RISE_last, df.REshare_last, c=df.Score, cmap=CMAP, norm=norm, s=size,
                edgecolor="white", linewidth=0.5, zorder=3)
label = {"Austria": (6, -10), "Norway": (8, 2), "Denmark": (6, 4), "New Zealand": (-66, 3),
         "Costa Rica": (-58, 0), "Brazil": (6, -11), "Uganda": (6, -3), "Germany": (6, 3),
         "France": (6, -3), "Chad": (5, 4), "Qatar": (-10, 9), "Mozambique": (-64, -6)}
for c, (dx, dy) in label.items():
    r = df[df.Country == c].iloc[0]
    ax.annotate(f"{c} ({r.Rank})", (r.RISE_last, r.REshare_last), xytext=(dx, dy),
                textcoords="offset points", fontsize=7, color="0.15", zorder=4)
ax.text(17, 104, "Weak policy", ha="center", fontsize=7, color="#b03a2e")
ax.text(50.5, 104, "Intermediate policy", ha="center", fontsize=7, color="#9a6b00")
ax.text(83.5, 104, "Strong policy", ha="center", fontsize=7, color="#1e7b45")
ax.set_xlim(0, 100); ax.set_ylim(0, 110)
ax.set_xlabel(f"RISE renewable-energy pillar score, {RY} (0–100)")
ax.set_ylabel(f"Renewable share of electricity, {AY} (%)")
cb = fig.colorbar(sc, ax=ax, pad=0.015, fraction=0.035)
cb.set_label(r"Final score $S(\gamma)$")
for v in (1, 5, 20, 45):
    ax.scatter([], [], s=12 + 9 * np.sqrt(v), color="0.6", edgecolor="white", label=f"{v} t")
fig.legend(title=rf"Marker size: CO$_2$ per capita, {AY}", loc="outside lower center", ncol=4,
           handletextpad=0.2, columnspacing=1.2)
save_png(fig, "fig_policy_matrix.png")
plt.close(fig)

# ---------------------------------------------------------------- world map
# Robinson projection implemented directly (standard Robinson table, linear interpolation),
# so the map needs only numpy and matplotlib (no geopandas or pyproj).
import json
from matplotlib.collections import PolyCollection

_LAT = np.arange(0, 95, 5)
_X = np.array([1.0000, 0.9986, 0.9954, 0.9900, 0.9822, 0.9730, 0.9600, 0.9427, 0.9216, 0.8962,
               0.8679, 0.8350, 0.7986, 0.7597, 0.7186, 0.6732, 0.6213, 0.5722, 0.5322])
_Y = np.array([0.0000, 0.0620, 0.1240, 0.1860, 0.2480, 0.3100, 0.3720, 0.4340, 0.4958, 0.5571,
               0.6176, 0.6769, 0.7346, 0.7903, 0.8435, 0.8936, 0.9394, 0.9761, 1.0000])


def robinson(lon, lat):
    lon, lat = np.asarray(lon, float), np.asarray(lat, float)
    a = np.abs(lat)
    x = 0.8487 * np.interp(a, _LAT, _X) * np.radians(lon)
    y = 1.3523 * np.interp(a, _LAT, _Y) * np.sign(lat)
    return x, y


with open(os.path.join(EXT, "ne_110m_admin_0_countries.geojson"), encoding="utf-8") as fh:
    features = json.load(fh)["features"]
score = dict(zip(df.ISO3, df.Score))
shapes, isos = [], set()          # (area, polygon, colour); drawn largest first so enclaves stay visible
for ft in features:
    pr = ft["properties"]
    if pr["ADM0_A3"] == "ATA":
        continue
    iso = pr["ISO_A3_EH"] if pr["ISO_A3_EH"] != "-99" else pr["ADM0_A3"]
    isos.add(iso)
    geom = ft["geometry"]
    parts = geom["coordinates"] if geom["type"] == "MultiPolygon" else [geom["coordinates"]]
    colour = CMAP(norm(score[iso])) if iso in score else "#e6e6e6"
    for part in parts:
        ring = np.asarray(part[0])
        xy = np.column_stack(robinson(ring[:, 0], ring[:, 1]))
        area = 0.5 * abs(np.dot(xy[:, 0], np.roll(xy[:, 1], 1)) - np.dot(xy[:, 1], np.roll(xy[:, 0], 1)))
        shapes.append((area, xy, colour))
shapes.sort(key=lambda s: -s[0])
fig, ax = plt.subplots(figsize=(fs.TEXTWIDTH_IN, 3.4), layout="none")
ax.add_collection(PolyCollection([s[1] for s in shapes], facecolors=[s[2] for s in shapes],
                                 edgecolor="white", linewidth=0.3))
allxy = np.vstack([s[1] for s in shapes])
ax.set_xlim(allxy[:, 0].min(), allxy[:, 0].max()); ax.set_ylim(allxy[:, 1].min(), allxy[:, 1].max())
ax.set_aspect("equal")
# top five: country location (lon, lat) and label position in open sea (lon, lat)
TOP = {"AUT": ((14.5, 47.5), (-24, 44)), "NOR": ((9.0, 61.0), (-22, 69)),
       "DNK": ((9.3, 56.0), (-24, 56.5)), "NZL": ((172.5, -41.5), (160, -52)),
       "CRI": ((-84.0, 9.8), (-100, 4))}
for iso, ((lon, lat), (llon, llat)) in TOP.items():
    rk = int(df.loc[df.ISO3 == iso, "Rank"].iloc[0])
    x, y = robinson(lon, lat); lx, ly = robinson(llon, llat)
    ax.plot([x, lx], [y, ly], color="#1f1f1f", lw=0.6, zorder=5)
    ax.plot(x, y, marker="o", ms=2.5, color="#1f1f1f", zorder=6)
    ax.plot(lx, ly, marker="o", ms=10, mfc="white", mec="#1f1f1f", mew=0.8, zorder=6)
    ax.text(lx, ly, str(rk), ha="center", va="center", fontsize=7, fontweight="bold", zorder=7)
ax.set_axis_off()
sm = plt.cm.ScalarMappable(cmap=CMAP, norm=norm)
cax = fig.add_axes([0.28, 0.13, 0.44, 0.028])
cb = fig.colorbar(sm, cax=cax, orientation="horizontal")
cb.set_label(r"Final score $S(\gamma)$ (grey: not in the panel; numbered circles: top five)", fontsize=8)
cb.ax.tick_params(labelsize=7)
fig.subplots_adjust(left=0, right=1, top=1, bottom=0.21)
save_png(fig, "fig_world_map.png")
plt.close(fig)
print(g[["band", "re", "n", "score", "med", "top20", "ex"]].to_string())
print("Panel countries too small for the 1:110m map:", sorted(set(df.ISO3) - isos))
